baseurl = "https://alientux.github.io/"
languageCode = "en"
title = "AlienTux"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
summarylength = 10
enableEmoji = true
paginate = 5
theme = "soho"
googleAnalytics = "UA-173499380-1"

[params]
title = "AlienTux"
description = "Un blog de tecnología, diseño, impresión 3d y mecatrónica"
# gravatar = "soho@example.com"
images = ["images/alien-tux.png"]
profilePicture = "images/alien-tux.png"
copyright = "AlienTux"
license = "CC BY-SA 4.0"
licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"
builtWith = true
mainSections = ["post"]

## Set custom theme color.
# themeColor = "3e432e"

## Set custom CSS and/or JS to override site defaults.
customCss = ["css/darkTheme.css"]
customJs = ["js/blog.js"]

  [[params.socialIcons]]
  icon = "fa-github"
  title = "GitHub"
  url = "https://github.com/alientux"

  [[params.socialIcons]]
  icon = "fa-twitter"
  title = "Twitter"
  url = "#"

  [[params.socialIcons]]
  icon = "fa-patreon"
  title = "Patreon"
  url = "https://patreon.com/AlienTux"

  [[params.socialIcons]]
  icon = "fa-youtube"
  title = "YouTube"
  url = "#"
  
  [[params.socialIcons]]
  icon = "fa-twitch"
  title = "Twitch"
  url = "https://twitch.com/alientux"

[taxonomies]
  series = "series"
  category = "categories"
  tag = "tags"

[menu]

  [[menu.main]]
  name = "Acerca de mí"
  identifier = "acercaDeMi"
  weight = 10
  url = "/acercaDeMi/"

  [[menu.main]]
  name = "Blog"
  weight = 100
  identifier = "posts"
  url = "/posts/"

  [[menu.main]]
  name = "Tutoriales"
  identifier = "tutoriales"
  weight = 110
  url = "/tutorial/"

  [[menu.main]]
  name = "Categorías"
  weight = 200
  identifier = "categories"
  url = "/categories/"

  [[menu.main]]
  name = "Tags"
  weight = 200
  identifier = "tags"
  url = "/tags/"

[markup]

  [markup.highlight]
  codeFences = true
  guessSyntax = false
  hl_Lines = ""
  lineNoStart = 1
  lineNos = false
  lineNumbersInTable = true
  noClasses = true
  style = "monokai"
  tabWidth = 4
